runtime: nodejs20

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/imip-387814:europe-west2:imip-project-db
  DB_USER: root
  DB_PASS: 4+G@KXb7K)xb6V2]
  DB_NAME: ticket_site
  MYSQL_HOST: '35.246.66.179'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '4+G@KXb7K)xb6V2]'
  MYSQL_DATABASE: 'ticket_site'
  STRIPE_SECRET_KEY: 'sk_test_51N18awJuWbWNbD9CTQvtSoZbMgmaO9hyWUEmh0Wo1LgBirNKA4sNdTVPWGmwhqKiLbIa5tHAo9UJFVxxbtwvoW1600P3oidqzR'
  STRIPE_PUB_KEY: 'pk_test_51N18awJuWbWNbD9CAMM1q21vR8i2Y7rKnYZmTJ2m3KFFAtSzbIoYlJ9AUrfdLh0j5EhnabkerAVWtTcbyUEssZij003TYkktpV'
  STRIPE_ENDPOINT_SECRET: ''
  SESSION_SECRET: 'secret'
  EMAIL_USERNAME: 'tix-fix@outlook.com'
  EMAIL_PASSWORD: 'tixfix15'